default_language_version:
  python: python3.11
exclude: '(\.eggs|\.git|\.hg|\.mypy_cache|\.idea|.idea|\.pytest_cache|\.tox|\.venv|venv|.env|env|\.vscode|static|media/|.*/templates|.*/migrations)'
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.292
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
##  # Exclude the black hook to disable line length checks
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        description: "Black: The uncompromising Python code formatter"
  - repo: local
    hooks:
      - id: migrations-check
        language: system
        name: Check for uncreated migrations.
        entry: sh -c "./manage.py makemigrations --check --dry-run"
        files: "models\\.py$"
        stages: [commit]
