# Generated by Django 4.2.6 on 2023-10-13 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="district",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="district",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="common.region"
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
