# Generated by Django 4.2.6 on 2023-10-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_alter_district_name_alter_district_region_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="district",
            name="created_time",
            field=models.DateTimeField(default="2023-03-13 12:22:00.634009+00"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="district",
            name="updated_time",
            field=models.DateTimeField(default="2023-03-13 12:22:00.634009+00"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="region",
            name="created_time",
            field=models.DateTimeField(default="2023-03-13 12:22:00.634009+00"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="region",
            name="updated_time",
            field=models.DateTimeField(default="2023-03-13 12:22:00.634009+00"),
            preserve_default=False,
        ),
    ]
