# Generated by Django 4.2.6 on 2023-10-13 10:00

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0004_district_name_ru_district_name_uz_region_name_ru_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="district",
            index=models.Index(
                models.OrderBy(
                    django.db.models.functions.text.Upper("name_uz"), descending=True
                ),
                name="district_name_uz_upper_index",
            ),
        ),
        migrations.AddIndex(
            model_name="district",
            index=models.Index(
                models.OrderBy(
                    django.db.models.functions.text.Upper("name_ru"), descending=True
                ),
                name="district_name_ru_upper_index",
            ),
        ),
        migrations.AddIndex(
            model_name="region",
            index=models.Index(
                models.OrderBy(
                    django.db.models.functions.text.Upper("name_uz"), descending=True
                ),
                name="region_name_uz_upper_index",
            ),
        ),
        migrations.AddIndex(
            model_name="region",
            index=models.Index(
                models.OrderBy(
                    django.db.models.functions.text.Upper("name_ru"), descending=True
                ),
                name="region_name_ru_upper_index",
            ),
        ),
    ]
