# Generated by Django 4.2.6 on 2023-10-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_district"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
